version: 2

updates:
  - package-ecosystem: nuget
    directories:
      - /ControlApp
      - /ControlApp.Tests
      - /SDK/Nefarius.DsHidMini.IPC
      - /ipctest
      - /build
      - /setup
    schedule:
      interval: weekly
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: weekly
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
