#pragma once

typedef UCHAR HID_REPORT_DESCRIPTOR, * PHID_REPORT_DESCRIPTOR;

extern CONST HID_REPORT_DESCRIPTOR G_Ds3HidReportDescriptor_Split_Mode[];

extern CONST HID_DESCRIPTOR G_Ds3HidDescriptor_Split_Mode;

extern CONST HID_REPORT_DESCRIPTOR G_Ds3HidReportDescriptor_Single_Mode[];

extern CONST HID_DESCRIPTOR G_Ds3HidDescriptor_Single_Mode;

extern CONST HID_REPORT_DESCRIPTOR G_SixaxisHidReportDescriptor[];

extern CONST HID_DESCRIPTOR G_SixaxisHidDescriptor;

extern CONST HID_REPORT_DESCRIPTOR G_VendorDefinedUSBDS4HidReportDescriptor[];

extern CONST HID_DESCRIPTOR G_VendorDefinedUSBDS4HidDescriptor;

extern CONST HID_REPORT_DESCRIPTOR G_XInputHIDCompatible_HidReportDescriptor[];

extern CONST HID_DESCRIPTOR G_XInputHIDCompatible_HidDescriptor;

#define DS3_COMMON_MAX_HID_INPUT_REPORT_SIZE	0x40
#define DS3_DS4REV1_USB_HID_INPUT_REPORT_SIZE	DS3_COMMON_MAX_HID_INPUT_REPORT_SIZE
#define DS3_SDF_GPJ_HID_INPUT_REPORT_SIZE		0x27
#define SIXAXIS_HID_INPUT_REPORT_SIZE			0x0C
#define SIXAXIS_HID_GET_FEATURE_REPORT_SIZE		0x31
#define XINPUTHID_HID_INPUT_REPORT_SIZE			0x11

#define DS3_RAW_SLIDER_IDLE_THRESHOLD			0x7F // 127 ( (256 * 0,5 ) -1 )
#define DS3_RAW_AXIS_IDLE_THRESHOLD_LOWER		0x3F // 63 ( ( 128 * 0,5 ) - 1 )
#define DS3_RAW_AXIS_IDLE_THRESHOLD_UPPER		0xC0 // 192 ( ( 128 * 1,5 ) - 1 )

// Artificial identifiers to ease detection
// 
#define DS3_DS4WINDOWS_HID_VID					0x7331
#define DS3_DS4WINDOWS_HID_PID					0x0001
#define DS3_XINPUT_HID_VID						0x045E
#define DS3_XINPUT_HID_PID						0x02FF


void DS3_RAW_AXIS_TRANSFORM(
	_In_ UCHAR InputX,
	_In_ UCHAR InputY,
	_Inout_ PUCHAR OutputX,
	_Inout_ PUCHAR OutputY,
	_In_ BOOLEAN ApplyDeadZone,
	_In_ DOUBLE DeadZonePolarValue,
	_In_ BOOLEAN FlipX,
	_In_ BOOLEAN FlipY
);

VOID DS3_RAW_TO_GPJ_HID_INPUT_REPORT_01(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PUCHAR Output,
	_In_ DS_PRESSURE_EXPOSURE_MODE PressureMode,
	_In_ DS_DPAD_EXPOSURE_MODE DPadExposureMode,
	_In_ PDS_THUMB_SETTINGS ThumbSettings,
	_In_ PDS_FLIP_AXIS_SETTINGS FlipAxis
);

VOID DS3_RAW_TO_GPJ_HID_INPUT_REPORT_02(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PUCHAR Output
);

VOID DS3_RAW_TO_SDF_HID_INPUT_REPORT(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PUCHAR Output,
	_In_ DS_PRESSURE_EXPOSURE_MODE PressureMode,
	_In_ DS_DPAD_EXPOSURE_MODE DPadExposureMode,
	_In_ PDS_THUMB_SETTINGS ThumbSettings,
	_In_ PDS_FLIP_AXIS_SETTINGS FlipAxis
);

VOID DS3_RAW_TO_SIXAXIS_HID_INPUT_REPORT(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PUCHAR Output,
	_In_ PDS_THUMB_SETTINGS ThumbSettings,
	_In_ PDS_FLIP_AXIS_SETTINGS FlipAxis
);

UCHAR REVERSE_BITS(UCHAR x);

VOID DS3_RAW_TO_DS4WINDOWS_HID_INPUT_REPORT(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PUCHAR Output,
	_In_ BOOLEAN IsWired,
	_In_ PDS_THUMB_SETTINGS ThumbSettings,
	_In_ PDS_FLIP_AXIS_SETTINGS FlipAxis
);

VOID DS3_RAW_TO_XINPUTHID_HID_INPUT_REPORT(
	_In_ PDS3_RAW_INPUT_REPORT Input,
	_Out_ PXINPUT_HID_INPUT_REPORT Output,
	_In_ PDS_THUMB_SETTINGS ThumbSettings,
	_In_ PDS_FLIP_AXIS_SETTINGS FlipAxis
);
